package com.example.psq.greendao.database;

import java.util.List;
import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;
import org.greenrobot.greendao.query.Query;
import org.greenrobot.greendao.query.QueryBuilder;

import com.example.psq.greendao.dao.AnswerDAO;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "ANSWER_DAO".
*/
public class AnswerDAODao extends AbstractDao<AnswerDAO, Long> {

    public static final String TABLENAME = "ANSWER_DAO";

    /**
     * Properties of entity AnswerDAO.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property AnsweredId = new Property(1, Long.class, "answeredId", false, "ANSWERED_ID");
        public final static Property AnswerId = new Property(2, String.class, "answerId", false, "ANSWER_ID");
        public final static Property BankId = new Property(3, String.class, "bankId", false, "BANK_ID");
        public final static Property Type = new Property(4, String.class, "type", false, "TYPE");
        public final static Property Title = new Property(5, String.class, "title", false, "TITLE");
        public final static Property Content = new Property(6, String.class, "content", false, "CONTENT");
        public final static Property Answer = new Property(7, String.class, "answer", false, "ANSWER");
    }

    private Query<AnswerDAO> answeredDAO_AnswerDAOSQuery;

    public AnswerDAODao(DaoConfig config) {
        super(config);
    }
    
    public AnswerDAODao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"ANSWER_DAO\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "\"ANSWERED_ID\" INTEGER," + // 1: answeredId
                "\"ANSWER_ID\" TEXT," + // 2: answerId
                "\"BANK_ID\" TEXT," + // 3: bankId
                "\"TYPE\" TEXT," + // 4: type
                "\"TITLE\" TEXT," + // 5: title
                "\"CONTENT\" TEXT," + // 6: content
                "\"ANSWER\" TEXT);"); // 7: answer
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"ANSWER_DAO\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, AnswerDAO entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        Long answeredId = entity.getAnsweredId();
        if (answeredId != null) {
            stmt.bindLong(2, answeredId);
        }
 
        String answerId = entity.getAnswerId();
        if (answerId != null) {
            stmt.bindString(3, answerId);
        }
 
        String bankId = entity.getBankId();
        if (bankId != null) {
            stmt.bindString(4, bankId);
        }
 
        String type = entity.getType();
        if (type != null) {
            stmt.bindString(5, type);
        }
 
        String title = entity.getTitle();
        if (title != null) {
            stmt.bindString(6, title);
        }
 
        String content = entity.getContent();
        if (content != null) {
            stmt.bindString(7, content);
        }
 
        String answer = entity.getAnswer();
        if (answer != null) {
            stmt.bindString(8, answer);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, AnswerDAO entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        Long answeredId = entity.getAnsweredId();
        if (answeredId != null) {
            stmt.bindLong(2, answeredId);
        }
 
        String answerId = entity.getAnswerId();
        if (answerId != null) {
            stmt.bindString(3, answerId);
        }
 
        String bankId = entity.getBankId();
        if (bankId != null) {
            stmt.bindString(4, bankId);
        }
 
        String type = entity.getType();
        if (type != null) {
            stmt.bindString(5, type);
        }
 
        String title = entity.getTitle();
        if (title != null) {
            stmt.bindString(6, title);
        }
 
        String content = entity.getContent();
        if (content != null) {
            stmt.bindString(7, content);
        }
 
        String answer = entity.getAnswer();
        if (answer != null) {
            stmt.bindString(8, answer);
        }
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public AnswerDAO readEntity(Cursor cursor, int offset) {
        AnswerDAO entity = new AnswerDAO( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getLong(offset + 1), // answeredId
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // answerId
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // bankId
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4), // type
            cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5), // title
            cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6), // content
            cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7) // answer
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, AnswerDAO entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setAnsweredId(cursor.isNull(offset + 1) ? null : cursor.getLong(offset + 1));
        entity.setAnswerId(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setBankId(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setType(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
        entity.setTitle(cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5));
        entity.setContent(cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6));
        entity.setAnswer(cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(AnswerDAO entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(AnswerDAO entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(AnswerDAO entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
    /** Internal query to resolve the "answerDAOS" to-many relationship of AnsweredDAO. */
    public List<AnswerDAO> _queryAnsweredDAO_AnswerDAOS(Long answeredId) {
        synchronized (this) {
            if (answeredDAO_AnswerDAOSQuery == null) {
                QueryBuilder<AnswerDAO> queryBuilder = queryBuilder();
                queryBuilder.where(Properties.AnsweredId.eq(null));
                answeredDAO_AnswerDAOSQuery = queryBuilder.build();
            }
        }
        Query<AnswerDAO> query = answeredDAO_AnswerDAOSQuery.forCurrentThread();
        query.setParameter(0, answeredId);
        return query.list();
    }

}
