package com.example.psq.greendao.database;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.example.psq.greendao.dao.AnswerDAO;
import com.example.psq.greendao.dao.AnsweredDAO;
import com.example.psq.greendao.dao.QBankDAO;
import com.example.psq.greendao.dao.TopicDAO;

import com.example.psq.greendao.database.AnswerDAODao;
import com.example.psq.greendao.database.AnsweredDAODao;
import com.example.psq.greendao.database.QBankDAODao;
import com.example.psq.greendao.database.TopicDAODao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig answerDAODaoConfig;
    private final DaoConfig answeredDAODaoConfig;
    private final DaoConfig qBankDAODaoConfig;
    private final DaoConfig topicDAODaoConfig;

    private final AnswerDAODao answerDAODao;
    private final AnsweredDAODao answeredDAODao;
    private final QBankDAODao qBankDAODao;
    private final TopicDAODao topicDAODao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        answerDAODaoConfig = daoConfigMap.get(AnswerDAODao.class).clone();
        answerDAODaoConfig.initIdentityScope(type);

        answeredDAODaoConfig = daoConfigMap.get(AnsweredDAODao.class).clone();
        answeredDAODaoConfig.initIdentityScope(type);

        qBankDAODaoConfig = daoConfigMap.get(QBankDAODao.class).clone();
        qBankDAODaoConfig.initIdentityScope(type);

        topicDAODaoConfig = daoConfigMap.get(TopicDAODao.class).clone();
        topicDAODaoConfig.initIdentityScope(type);

        answerDAODao = new AnswerDAODao(answerDAODaoConfig, this);
        answeredDAODao = new AnsweredDAODao(answeredDAODaoConfig, this);
        qBankDAODao = new QBankDAODao(qBankDAODaoConfig, this);
        topicDAODao = new TopicDAODao(topicDAODaoConfig, this);

        registerDao(AnswerDAO.class, answerDAODao);
        registerDao(AnsweredDAO.class, answeredDAODao);
        registerDao(QBankDAO.class, qBankDAODao);
        registerDao(TopicDAO.class, topicDAODao);
    }
    
    public void clear() {
        answerDAODaoConfig.clearIdentityScope();
        answeredDAODaoConfig.clearIdentityScope();
        qBankDAODaoConfig.clearIdentityScope();
        topicDAODaoConfig.clearIdentityScope();
    }

    public AnswerDAODao getAnswerDAODao() {
        return answerDAODao;
    }

    public AnsweredDAODao getAnsweredDAODao() {
        return answeredDAODao;
    }

    public QBankDAODao getQBankDAODao() {
        return qBankDAODao;
    }

    public TopicDAODao getTopicDAODao() {
        return topicDAODao;
    }

}
